import { addDoc, collection } from "firebase/firestore";
import { db } from "../Config/FirebaseConfig";

const products = [
    {name:"ADIDAS PREDATOR ACCURACY .1 FG", img: "https://assets.adidas.com/images/w_766,h_766,f_auto,q_auto,fl_lossy,c_fill,g_auto/8eb689fadc7c4a97bd04b21d718d2972_9366/copa-mundial.jpg", price: 249.99, category: "Botas", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black.", stock:10 },
    {name:"ADIDAS PREDATOR ACCURACY .1 FG", img: "https://www.futbolemotion.com/imagesarticulos/221083/detalles/P1GC244245_9.jpg", price: 249.99, category: "botas", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black", stock:10 },
    {name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category:"botas", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/detalles/P1GC244245_9.jpg", stock:10},
    {name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "botas", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/detalles/P1GC244245_9.jpg", stock:10 },
    {name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "guantes", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/detalles/P1GC244245_9.jpg", stock:10 },
    {name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "guantes", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/detalles/P1GC244245_9.jpg", stock:10 },
    {name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "guantes", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/detalles/P1GC244245_9.jpg", stock:10 },
    {name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "guantes", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/detalles/P1GC244245_9.jpg", stock:10 },
    {name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "equipacion", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/detalles/P1GC244245_9.jpg", stock:10 },
    { name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "equipacion", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/detalles/P1GC244245_9.jpg", stock:10 },
    { name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "equipacion", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/detalles/P1GC244245_9.jpg", stock:10 },
    { name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "equipacion", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/grandes/bota-mizuno-morelia-neo-iv-elite-mix-yellow-0.webp", stock:10 },
    { name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "accesorios", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/grandes/bota-mizuno-morelia-neo-iv-elite-mix-yellow-0.webp", stock:10 },
    { name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "accesorios", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/grandes/bota-mizuno-morelia-neo-iv-elite-mix-yellow-0.webp", stock:10 },
    { name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "accesorios", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/grandes/bota-mizuno-morelia-neo-iv-elite-mix-yellow-0.webp", stock:10 },
    { name:"ADIDAS PREDATOR ACCURACY .1 FG", price: 99.99, category: "accesorios", description:"Bota de fútbol adidas Predator Accuracy.1 FG para adultos. Botas sintéticas con cordones para utilizar en campos de hierba natural. Botas de gama alta en color Solar Orange-Core Black",img: "https://www.futbolemotion.com/imagesarticulos/221083/grandes/bota-mizuno-morelia-neo-iv-elite-mix-yellow-0.webp", stock:10 },
    ];

    export const seedProducts = () =>{
        products.forEach( product => {
            addDoc(collection (db, "products"), product)
        })
    }